version: "3.7"

services:
  service:
    container_name: nextcloud-mautils
    image: nextcloud-mautils
    build:
      context: .
    restart: unless-stopped

networks:
  default:
    external:
      name: caddynet
